version: '3.8'

services:
  project4-llm:
    build: .
    container_name: project4-llm
    ports:
      - "8001:8001"
    environment:
      - ENV_TYPE=dev
      - OLLAMA_PORT=11434
    volumes:
      - logs:/app/logs
    network_mode: "host"


volumes:
  logs: